server:
  port: 8081

netty:
  ip: 127.0.0.1
  port: 7397

spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  datasource:
    username: root
    password: wswbh
    url: jdbc:mysql://127.0.0.1:3306/itstack?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      max-active: 20
      initial-size: 1
      min-idle: 1
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 20
      pool-prepared-statements: true

mybatis-plus:
  mapper-package: cn.chat.server.mapper
  mapper-locations: classpath*:/mapper/**/*.xml
  typeAliasesPackage: cn.chat.server.infrastructure
  configuration:
    map-underscore-to-camel-case: true
    #mybatis-plus配置控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cacheEnabled: false
  global-config:
    banner: false
    db-config:
      id-type: input

logging:
  level:
    cn.chat: debug
